/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type TextMedia = {
  _type: "textMedia";
  content?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  } | {
    text?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "textObject";
    _key: string;
  }>;
};

export type PlaceholderString = string;

export type ExternalLink = {
  _type: "externalLink";
  text?: string;
  url?: string;
  newWindow?: boolean;
};

export type InternalLink = {
  _type: "internalLink";
  reference?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "home";
  };
  text?: string;
};

export type PageHero = {
  _type: "pageHero";
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Gallery = {
  _type: "gallery";
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuItems?: Array<({
    _key: string;
  } & InternalLink) | ({
    _key: string;
  } & ExternalLink)>;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  blocks?: Array<({
    _key: string;
  } & Gallery) | ({
    _key: string;
  } & PageHero) | ({
    _key: string;
  } & TextMedia)>;
  seo?: SeoHome;
};

export type SeoHome = {
  _type: "seo.home";
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  blocks?: Array<({
    _key: string;
  } & Gallery) | ({
    _key: string;
  } & PageHero) | ({
    _key: string;
  } & TextMedia)>;
  seo?: SeoPage;
};

export type SeoPage = {
  _type: "seo.page";
  title?: PlaceholderString;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};
export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: app/sitemap.ts
// Variable: allSlugsQuery
export type AllSlugsQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: pageQuery
export type PageQueryResult = {
  blocks: null;
  seo: {
    description: null;
    image: null;
    title: null;
  };
} | {
  blocks: null;
  seo: {
    description: null;
    image: null;
    title: null | string;
  };
} | {
  blocks: Array<{} | TextMediaBlock | PageHeroBlock> | null;
  seo: {
    description: string | null;
    image: SanityImageFragment | null;
    title: PlaceholderString | string | null;
  };
} | {
  blocks: Array<{} | TextMediaBlock | PageHeroBlock> | null;
  seo: {
    description: string | null;
    image: SanityImageFragment | null;
    title: string | null;
  };
} | null;
// Variable: settingsQuery
export type SettingsQueryResult = {
  menuItems: Array<{
    _key: string;
    _type: "externalLink";
    text: string | null;
    url: string | null;
    newWindow: boolean | null;
  } | {
    _key: string;
    _type: "internalLink";
    text: string | null;
    slug: string | null;
  }> | null;
} | null;
// Variable: homePageQuery
export type HomePageQueryResult = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  blocks: Array<{} | TextMediaBlock | PageHeroBlock> | null;
  seo: {
    description: string | null;
    image: SanityImageFragment | null;
    title: string | null;
  };
} | null;



export type SanityImageFragment = {
      _key: string;
      _type: "image";
      id: string | null;
      preview: string | null;
      hotspot: {
        x: number | null;
        y: number | null;
      } | null;
      crop: {
        bottom: number | null;
        left: number | null;
        right: number | null;
        top: number | null;
      } | null;
      alt: string | null;
      tags: null;
      description: string | null;
      title: string | null;
      height: number | null;
      url: string | null;
      width: number | null;
      _ts: "SanityImageFragment";
    };


export type TextMediaBlock = {
    content: Array<SanityImageFragment | {
      _type: "textObject";
      _key: string;
      text: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h1" | "h2" | "h3" | "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
      }> | null;
    }> | null;
    _ts: "TextMediaBlock";
  };


export type PageHeroBlock = {
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
    }> | null;
    images: Array<SanityImageFragment> | null;
    _ts: "PageHeroBlock";
  };
