services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        VARIANT: 23-bookworm
    networks:
      - default
    volumes:
      - ..:/workspace/${COMPOSE_PROJECT_NAME}:cached
      - node_modules:/workspace/${COMPOSE_PROJECT_NAME}/node_modules/.pnpm
      - pnpm_store:/home/node/.pnpm-store
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node_modules:
  pnpm_store:
    external: true
